#!/usr/bin/env bash
set -euo pipefail

readonly BASH_COMPLETIONS_DIR="completions/bash"
readonly STUBS_DIR="completions"
readonly GENERATED_MARKER="# Generated by scripts/generate-bash-completion-stubs.sh; do not edit."

registered_commands() {
    local completion_file=$1

    zsh -f -c '
        autoload -Uz compinit bashcompinit
        compinit -D
        bashcompinit

        typeset -A registrations_before
        registrations_before=("${(@kv)_comps}")
        source "$1"

        local command registration
        for command registration in "${(@kv)_comps}"; do
            if [[ "${registrations_before[$command]-}" != "$registration" && "$registration" == "_bash_complete "* ]]; then
                print -r -- "$command"
            fi
        done
    ' zsh "$completion_file" | sort --unique
}

write_stub() {
    local completion_file=$1
    local stub_file=$2
    shift 2
    local -a commands=("$@")
    local command_list
    command_list=$(printf '%s ' "${commands[@]}")
    command_list=${command_list% }

    cat >"$stub_file" <<EOF
#compdef ${command_list}
${GENERATED_MARKER}
# Lazily loads ${completion_file} when one of its registered commands first
# requests completion, then delegates the current request to bashcompinit.
autoload -Uz bashcompinit
bashcompinit
source "\${ZUSH_BASH_COMPLETIONS_DIR}/${completion_file}"

local bash_completion="\${_comps[\$service]-}"
[[ "\$bash_completion" == '_bash_complete '* ]] || return 1
eval "\$bash_completion"
EOF
}

main() {
    local root
    root=$(git rev-parse --show-toplevel)
    cd "$root"

    mkdir -p "$STUBS_DIR"

    local -A expected_stubs=()
    local completion_path completion_file stem stub_name stub_path
    local -a commands
    shopt -s nullglob
    for completion_path in "$BASH_COMPLETIONS_DIR"/*.bash; do
        completion_file=${completion_path##*/}
        stem=${completion_file%.bash}
        [[ $stem =~ ^[A-Za-z0-9_.-]+$ ]] || {
            echo "Unsupported Bash completion filename: $completion_file" >&2
            return 1
        }

        stub_name="_bash_${stem//[.-]/_}"
        stub_path="${STUBS_DIR}/${stub_name}"
        [[ -z ${expected_stubs[$stub_name]+present} ]] || {
            echo "Bash completion stub name collision: $stub_name" >&2
            return 1
        }
        expected_stubs[$stub_name]=1

        mapfile -t commands < <(registered_commands "$completion_path")
        ((${#commands[@]} > 0)) || {
            echo "No Bash completion registrations found in $completion_file" >&2
            return 1
        }

        local command
        for command in "${commands[@]}"; do
            [[ $command =~ ^[A-Za-z0-9_.+-]+$ ]] || {
                echo "Unsupported command name '$command' in $completion_file" >&2
                return 1
            }
        done

        write_stub "$completion_file" "$stub_path" "${commands[@]}"
    done

    for stub_path in "$STUBS_DIR"/_bash_*; do
        stub_name=${stub_path##*/}
        [[ -n ${expected_stubs[$stub_name]+present} ]] && continue
        [[ $(sed -n '2p' "$stub_path") == "$GENERATED_MARKER" ]] || continue
        rm -- "$stub_path"
    done
}

main "$@"
